name: SupplyPackagesV2
version: ${project.version}
main: me.heknon.supplypackagesv2.SupplyPackagesV2
authors: [Heknon]
description: Replication of SupplyPackage plugin on spigot but without all the bugs.
commands:
  supplypackages:
    aliases:
      - supplypackage
      - sp
    description: Run this command to view a list of all commands.
permissions:
  supplypackages.help:
    description: View help page
    default: op
  supplypackages.summon:
    description: summon package
    default: op
  supplypackages.givesignal:
    description: give signal to a player
    default: op
  supplypackages.reload:
    description: reload the config
    default: op
  supplypackages.additem:
    description: add item to a package
    default: op
  supplypackages.resetitems:
    description: reset the package items
    default: op