name: SupplyPackagesV2
version: ${project.version}
main: me.heknon.supplypackagesv2.SupplyPackagesV2
authors: [Heknon]
description: Replication of SupplyPackage plugin on spigot but without all the bugs.
commands:
  supplypackages:
    aliases:
      - supplypackage
      - sp
    description: Run this command to view a list of all commands.