# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html  <<< ALL Block types || DO NOT USE DEPRECATED!
falling_from_sky_summoned_block: "BEACON" # The type of block that is falling from the sky upon summoning the Supply Package

block_material_on_hit: "JUKEBOX"

blocks_above_player_summoned_block: 200 # How many blocks above the player should the block that is summoned, be summoned above the player.

stop_at_water: false # Should the falling block stop at a water block or sink?

falling_block_speed_X_Vector: 0.0 # Vector... The lower the faster
falling_block_speed_Y_Vector: -1.0 # Vector... The lower the faster
falling_block_speed_Z_Vector: 0.0 # Vector... The lower the faster

allow_package_summoning_from_console: true # Pretty self explanatory.

permanent_effect_until_right_click: "ENDER_SIGNAL" # Effect shown until player right clicks to receive rewards.
data_of_permanent_effect_until_right_click: "100" # I dont know what this is but yes
effect_at_right_click_on_ground: "MOBSPAWNER_FLAMES" # Effect shown when right clicking the supply package after it hit the ground. Get all effects at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Effect.html || Enter disable to disable
data_of_effect_at_right_click_on_ground: "100" # I dont know what this is but yes
amount_of_fireworks_to_spawn_on_summon: 3
color_of_fire_work: "RED" # All colors https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Color.html

firework_meta:
  display_name: "&c&lSupply&f&lPackages"
  lore:
    [
     "&6Launch this firework",
     "&6to summon a SupplyPackage"
    ]










falling_block_uuid: "" # Do not change!